### ISSUE TITLE
Document recent changes view should cover entire work area

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#267]

**Comment by goose-life** [comment]
![image](https://user-images.githubusercontent.com/32566441/58622782-b7cb3d00-82cc-11e9-93a8-69781aaac80c.png)

**Comment by goose-life** [comment]
scroll bar still goes off the page, and can no longer scroll to earlier 'recent changes' in the right-hand pane

**Comment by longhotsummer** [comment]
Fixed again.

**Comment by goose-life** [comment]
scroll bar still going off the page and still unable to scroll to earlier versions?
also, can no longer use down arrow to keep scrolling when scroll bar runs off page
https://edit.laws.africa/documents/2293/
![image](https://user-images.githubusercontent.com/32566441/58976959-f9764f00-87c8-11e9-987a-bb9b8a581726.png)

**Comment by longhotsummer** [comment]
Looks like it works on Chrome, but not FF.

**Comment by longhotsummer** [comment]
@goose-life I can't reproduce this on chrome or FF. Can we take a look together on your machine when we're in the office next week?
